# Generated by Django 6.0.6 on 2026-06-24 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='titulo',
            field=models.CharField(default='Notificação', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.target'),
        ),
    ]
